
a_states = [
    {"name":"Alabama",
     "capitol":"Montgomery",
     "largest_city":"Birmingham"},
    {"name":"Alaska",
     "capitol":"Juneau",
     "largest_city":"Anchorage"},
    {"name":"Arizona",
     "capitol":"Phoenix",
     "largest_city":"Phoenix"},
    {"name":"Arkansas",
     "capitol":"Little Rock",
     "largest_city":"Little Rock"}
    ]

c_states = [
    {"name":"California",
     "capitol":"Sacramento",
     "largest_city":"Los Angeles"},
    {"name":"Colorado",
     "capitol":"Denver",
     "largest_city":"Denver"},
    {"name":"Connecticut",
     "capitol":"Hartford",
     "largest_city":"Bridgeport"}
]    

i_states = [
    {"name":"Idaho",
     "capitol":"Boise",
     "largest_city":"Boise"},
    {"name":"Illinois",
     "capitol":"Springfield",
     "largest_city":"Chicago"},
    {"name":"Indiana",
     "capitol":"Indianapolis",
     "largest_city":"Indianapolis"},
    {"name":"Iowa",
     "capitol":"Des Moines",
     "largest_city":"Des Moines"},
]

n_states = [
    {"name":"Nebraska",
     "capitol":"Lincoln",
     "largest_city":"Omaha"},
    {"name":"Nevada",
     "capitol":"Carson City",
     "largest_city":"Las Vegas"},
    {"name":"New Hampshire",
     "capitol":"Concord",
     "largest_city":"Manchester"},
    {"name":"New Jersey",
     "capitol":"Trenton",
     "largest_city":"Newark"},
    {"name":"New Mexico",
     "capitol":"Santa Fe",
     "largest_city":"Albuquerque"},
    {"name":"New York",
     "capitol":"Albany",
     "largest_city":"New York City"},
    {"name":"North Carolina",
     "capitol":"Raleigh",
     "largest_city":"Charlotte"},
    {"name":"North Dakota",
     "capitol":"Bismarck",
     "largest_city":"Fargo"},
    ]


s_states = [
    {"name":"South Carolina",
     "capitol":"Columbia",
     "largest_city":"Columbia"},
    {"name":"South Dakota",
     "capitol":"Pierre",
     "largest_city":"Sioux Falls"},
]

v_states = [
    {"name":"Vermont",
     "capitol":"Montpelier",
     "largest_city":"Burlington"},
    {"name":"Virginia",
     "capitol":"Richmond",
     "largest_city":"Virginia Beach"},
]

states = [
    {"name":"Alabama",
     "capitol":"Montgomery",
     "largest_city":"Birmingham"},
    {"name":"Alaska",
     "capitol":"Juneau",
     "largest_city":"Anchorage"},
    {"name":"Arizona",
     "capitol":"Phoenix",
     "largest_city":"Phoenix"},
    {"name":"Arkansas",
     "capitol":"Little Rock",
     "largest_city":"Little Rock"},
    {"name":"California",
     "capitol":"Sacramento",
     "largest_city":"Los Angeles"},
    {"name":"Colorado",
     "capitol":"Denver",
     "largest_city":"Denver"},
    {"name":"Connecticut",
     "capitol":"Hartford",
     "largest_city":"Bridgeport"},
    {"name":"Delaware",
     "capitol":"Dover",
     "largest_city":"Wilmington"},
    {"name":"Florida",
     "capitol":"Tallahassee",
     "largest_city":"Jacksonville"},
    {"name":"Georgia",
     "capitol":"Atlanta",
     "largest_city":"Atlanta"},
    {"name":"Hawaii",
     "capitol":"Honolulu",
     "largest_city":"Honolulu"},
    {"name":"Idaho",
     "capitol":"Boise",
     "largest_city":"Boise"},
    {"name":"Illinois",
     "capitol":"Springfield",
     "largest_city":"Chicago"},
    {"name":"Indiana",
     "capitol":"Indianapolis",
     "largest_city":"Indianapolis"},
    {"name":"Iowa",
     "capitol":"Des Moines",
     "largest_city":"Des Moines"},
    {"name":"Kansas",
     "capitol":"Topeka",
     "largest_city":"Wichita"},
    {"name":"Kentucky",
     "capitol":"Frankfort",
     "largest_city":"Louisville"},
    {"name":"Louisiana",
     "capitol":"Baton Rouge",
     "largest_city":"New Orleans"},
    {"name":"Maine",
     "capitol":"Augusta",
     "largest_city":"Portland"},
    {"name":"Maryland",
     "capitol":"Annapolis",
     "largest_city":"Baltimore"},
    {"name":"Massachusetts",
     "capitol":"Boston",
     "largest_city":"Boston"},
    {"name":"Michigan",
     "capitol":"Lansing",
     "largest_city":"Detroit"},
    {"name":" Minnesota",
     "capitol":"St. Paul",
     "largest_city":"Minneapolis"},
    {"name":"Mississippi",
     "capitol":"Jackson",
     "largest_city":"Jackson"},
    {"name":"Missouri",
     "capitol":"Jefferson City",
     "largest_city":"Kansas City"},
    {"name":"Montana",
     "capitol":"Helena",
     "largest_city":"Billings"},
    {"name":"Nebraska",
     "capitol":"Lincoln",
     "largest_city":"Omaha"},
    {"name":"Nevada",
     "capitol":"Carson City",
     "largest_city":"Las Vegas"},
    {"name":"New Hampshire",
     "capitol":"Concord",
     "largest_city":"Manchester"},
    {"name":"New Jersey",
     "capitol":"Trenton",
     "largest_city":"Newark"},
    {"name":"New Mexico",
     "capitol":"Santa Fe",
     "largest_city":"Albuquerque"},
    {"name":"New York",
     "capitol":"Albany",
     "largest_city":"New York City"},
    {"name":"North Carolina",
     "capitol":"Raleigh",
     "largest_city":"Charlotte"},
    {"name":"North Dakota",
     "capitol":"Bismarck",
     "largest_city":"Fargo"},
    {"name":"Ohio",
     "capitol":"Columbus",
     "largest_city":"Columbus"},
    {"name":"Oklahoma",
     "capitol":"Oklahoma City",
     "largest_city":"Oklahoma City"},
    {"name":"Oregon",
     "capitol":"Salem",
     "largest_city":"Portland"},
    {"name":"Pennsylvania",
     "capitol":"Harrisburg",
     "largest_city":"Philadelphia"},
    {"name":"Rhode Island",
     "capitol":"Providence",
     "largest_city":"Providence"},
    {"name":"South Carolina",
     "capitol":"Columbia",
     "largest_city":"Columbia"},
    {"name":"South Dakota",
     "capitol":"Pierre",
     "largest_city":"Sioux Falls"},
    {"name":"Tennessee",
     "capitol":"Nashville",
     "largest_city":"Memphis"},
    {"name":"Texas",
     "capitol":"Austin",
     "largest_city":"Houston"},
    {"name":"Utah",
     "capitol":"Salt Lake City",
     "largest_city":"Salt Lake City"},
    {"name":"Vermont",
     "capitol":"Montpelier",
     "largest_city":"Burlington"},
    {"name":"Virginia",
     "capitol":"Richmond",
     "largest_city":"Virginia Beach"},
    {"name":"Washington",
     "capitol":"Olympia",
     "largest_city":"Seattle"},
    {"name":"West Virginia",
     "capitol":"Charleston",
     "largest_city":"Charleston"},
    {"name":"Wisconsin",
     "capitol":"Madison",
     "largest_city":"Milwaukee"},
    {"name":"Wyoming",
     "capitol":"Cheyenne",
     "largest_city":"Cheyenne"}
]
